In [250]:
import unicodedata

from string import ascii_lowercase
from numpy import logical_not
import pandas as pd
import pyperclip
from fuzzyfinder import fuzzyfinder
from prompt_toolkit import prompt
from prompt_toolkit.completion import Completer, Completion
from prompt_toolkit.validation import ValidationError, Validator

df = pd.read_csv("../UnicodeData.txt", sep=";", header=None)
df = df[[0, 1]]
df = df.rename(columns={0: "code", 1: "name"})
df = df[["name", "code"]]
df["char"] = [chr(int(c, 16)) for c in df["code"]]
df["cat"] = [unicodedata.category(v) for v in df["char"]]
df["bidic"] = [unicodedata.bidirectional(v) for v in df["char"]]
df["name"] = [name.lower() for name in df["name"]]
df["sorted_name"] = [" ".join(sorted(name.split(" "))) for name in df["name"]]

df = df[df["cat"] != "Cc"]
df = df[df["cat"] != "Cf"]

alphabets = pd.read_csv("alphabets.csv", header=None)
alphabets = [alphabets.iloc[i].values[0].lower() for i in range(alphabets.shape[0])]
alphabets = [a for a in alphabets if a not in ["latin", "greek"]]

for alphabet in alphabets:
    df = df[logical_not(df["name"].str.startswith(alphabet))]

df = df[logical_not(df["name"].str.startswith("variation"))]
df = df[logical_not(df["name"].str.startswith("tag"))]
df = df[logical_not(df["name"].str.contains("cjk"))]
df = df[logical_not(df["name"].str.contains("xiangqi"))]
df = df[logical_not(df["name"].str.contains("<plane"))]
df = df[logical_not(df["name"].str.contains("canadian"))]
df = df[logical_not(df["name"].str.contains("braille"))]
df = df[logical_not(df["name"].str.contains("ethiopic"))]
df = df[logical_not(df["name"].str.contains("kangxi"))]
df = df[logical_not(df["name"].str.contains("ideographic"))]
df = df[logical_not(df["name"].str.contains("japanese"))]
df = df[logical_not(df["name"].str.contains("ideographic"))]
df = df[logical_not(df["name"].str.contains("hiragana"))]
df = df[logical_not(df["name"].str.contains("hexagram"))]
df = df[logical_not(df["name"].str.contains("yi syllable"))]
df = df[logical_not(df["name"].str.contains("old turkic"))]
df = df[logical_not(df["name"].str.contains("cuneiform"))]
df = df[logical_not(df["name"].str.contains("egyptian"))]
df = df[logical_not(df["name"].str.contains("anatolian"))]
df = df[logical_not(df["name"].str.contains("nushu"))]
df = df[logical_not(df["name"].str.contains("hentaigana"))]
df = df[logical_not(df["name"].str.contains("nyiakeng"))]
df = df[logical_not(df["name"].str.contains("katakana"))]
df = df[logical_not(df["name"].str.contains("vai syllable"))]
df = df[logical_not(df["name"].str.contains("ideogram"))]
df = df[logical_not(df["name"].str.contains("hungarian"))]
df = df[logical_not(df["name"].str.contains("zanabazar"))]
df = df[logical_not(df["name"].str.contains("bhaiksuki"))]
df = df[logical_not(df["name"].str.contains("marchen"))]
df = df[logical_not(df["name"].str.contains("tangut"))]
df = df[logical_not(df["name"].str.contains("miao"))]
df = df[logical_not(df["name"].str.contains("medefaidrin"))]
df = df[logical_not(df["name"].str.contains("masaram"))]
df = df[logical_not(df["name"].str.contains("warang"))]
df = df[logical_not(df["name"].str.contains("duployan"))]
df = df[logical_not(df["name"].str.contains("byzantine"))]
df = df[logical_not(df["name"].str.contains("signwriting"))]
df = df[logical_not(df["name"].str.contains("wancho"))]
df = df[logical_not(df["name"].str.contains("mahjong"))]
df = df[logical_not(df["name"].str.contains("alchemical"))]
df = df[logical_not(df["name"].str.contains("cyrillic"))]
df = df[logical_not(df["name"].str.contains("ogham"))]
df = df[logical_not(df["name"].str.contains("bopomofo"))]
df = df[logical_not(df["name"].str.contains("phaistos"))]
df = df[logical_not(df["name"].str.contains("osage"))]
df = df[logical_not(df["name"].str.contains("meroitic"))]
df = df[logical_not(df["name"].str.contains("inscriptional"))]
df = df[logical_not(df["name"].str.contains("hanifi"))]
df = df[logical_not(df["name"].str.contains("rumi"))]
df = df[logical_not(df["name"].str.contains("sogdian"))]
df = df[logical_not(df["name"].str.contains("elymaic"))]
df = df[logical_not(df["name"].str.contains("multani"))]
df = df[logical_not(df["name"].str.contains("dogra"))]
df = df[logical_not(df["name"].str.contains("soyombo"))]
df = df[logical_not(df["name"].str.contains("gunjala"))]
df = df[logical_not(df["name"].str.contains("makasar"))]
df = df[logical_not(df["name"].str.contains("tetragram"))]
df = df[logical_not(df["name"].str.contains("adlam"))]
df = df[logical_not(df["name"].str.contains("indic"))]
df = df[logical_not(df["name"].str.contains("domino"))]
df = df[logical_not(df["name"].str.contains("hangul"))]
df = df[logical_not(df["name"].str.contains("ideograph"))]
df = df[logical_not(df["name"].str.contains("cypriot"))]
df = df[logical_not(df["name"].str.contains("pahlavi"))]
df = df[logical_not(df["name"].str.contains("nandinagari"))]
df = df[logical_not(df["name"].str.contains("bassa"))]

df = df.reset_index(drop=True)
idx = []
for i in range(df.shape[0]):
    try:
        df.iloc[i]["char"].encode("utf8")
    except:
        idx.append(i)
df = df.iloc[list(set(range(df.shape[0])) - set(idx))]
df = df.reset_index(drop=True)

In [252]:
df.to_pickle("../unicode_clean1.pkl", protocol=-1)

In [281]:
df = pd.read_pickle("../unicode_clean1.pkl")

def append(df, values):
    cols = ["name", "code", "char", "cat", "bidic", "sorted_name"]
    d = dict(zip(cols, values))
    return df.append(d, ignore_index = True)

def _append(df, name, s):
    df0 = df[df["name"] == name]
    if df0.shape[0] == 0:
        return df
    code = df0["code"].values[0]
    ch = df0["char"].values[0]
    cat = df0["cat"].values[0]
    bidic = df0["bidic"].values[0]
    return append(df, [s, code, ch, cat, bidic, s])

numbers = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
for i, num in enumerate(numbers):
    df0 = df[df["name"] == f"superscript {num}"]
    code = df0["code"].values[0]
    ch = df0["char"].values[0]
    cat = df0["cat"].values[0]
    bidic = df0["bidic"].values[0]
    df = append(df, [f"^{i}", code, ch, cat, bidic, f"^{i}"])

for i, num in enumerate(numbers):
    df0 = df[df["name"] == f"subscript {num}"]
    code = df0["code"].values[0]
    ch = df0["char"].values[0]
    cat = df0["cat"].values[0]
    bidic = df0["bidic"].values[0]
    df = append(df, [f"_{i}", code, ch, cat, bidic, f"_{i}"])

names = ["superscript left parenthesis", "superscript right parenthesis",
         "superscript minus", "superscript plus sign", "superscript equals sign"]
shortcut = ["^(", "^)", "^-", "^+", "^="]

for i, name in enumerate(names):
    df0 = df[df["name"] == name]
    code = df0["code"].values[0]
    ch = df0["char"].values[0]
    cat = df0["cat"].values[0]
    bidic = df0["bidic"].values[0]
    s = shortcut[i]
    df = append(df, [s, code, ch, cat, bidic, s])

for a in ascii_lowercase:
    name = f"superscript latin small letter {a}"
    df0 = df[df["name"] == name]
    if df0.shape[0] == 0:
        continue
    code = df0["code"].values[0]
    ch = df0["char"].values[0]
    cat = df0["cat"].values[0]
    bidic = df0["bidic"].values[0]
    df = append(df, [f"^{a}", code, ch, cat, bidic, f"^{a}"])

names = ["subscript left parenthesis", "subscript right parenthesis",
         "subscript minus", "subscript plus sign", "subscript equals sign"]
shortcut = ["_(", "_)", "_-", "_+", "_="]

for i, name in enumerate(names):
    df0 = df[df["name"] == name]
    code = df0["code"].values[0]
    ch = df0["char"].values[0]
    cat = df0["cat"].values[0]
    bidic = df0["bidic"].values[0]
    s = shortcut[i]
    df = append(df, [s, code, ch, cat, bidic, s])
    
for a in ascii_lowercase:
    name = f"latin subscript small letter {a}"
    df0 = df[df["name"] == name]
    if df0.shape[0] == 0:
        continue
    code = df0["code"].values[0]
    ch = df0["char"].values[0]
    cat = df0["cat"].values[0]
    bidic = df0["bidic"].values[0]
    df = append(df, [f"_{a}", code, ch, cat, bidic, f"_{a}"])

df = _append(df, "mathematical italic small beta", r"\beta")

In [282]:
df.tail()

       name   code char cat bidic sorted_name
9340     _t   209C    ₜ  Lm     L          _t
9341     _u   1D64    ᵤ  Lm     L          _u
9342     _v   1D65    ᵥ  Lm     L          _v
9343     _x   2093    ₓ  Lm     L          _x
9344  \beta  1D6FD    𝛽  Ll     L       \beta

In [279]:
df[df["name"].str.contains("LATIN SUBSCRIPT SMALL LETTER A".lower())]

,name,code,char,cat,bidic,sorted_name
1693,latin subscript small letter a,2090,ₐ,Lm,L,a latin letter small subscript

In [253]:
# df = pd.read_csv("../UnicodeData.txt", sep=";", header=None)
# df = df[[0, 1]]
# df = df.rename(columns={0: "code", 1: "name"})
# df = df[["name", "code"]]
# df["char"] = [chr(int(c, 16)) for c in df["code"]]
# df["cat"] = [unicodedata.category(v) for v in df["char"]]
# df["bidic"] = [unicodedata.bidirectional(v) for v in df["char"]]
# df["name"] = [name.lower() for name in df["name"]]
# df["sorted_name"] = [" ".join(sorted(name.split(" "))) for name in df["name"]]

df = pd.read_pickle("../unicode_clean1.pkl")


df[df["name"].str.contains("subscript")]

,name,code,char,cat,bidic,sorted_name
970,latin subscript small letter i,1D62,ᵢ,Lm,L,i latin letter small subscript
971,latin subscript small letter r,1D63,ᵣ,Lm,L,latin letter r small subscript
972,latin subscript small letter u,1D64,ᵤ,Lm,L,latin letter small subscript u
973,latin subscript small letter v,1D65,ᵥ,Lm,L,latin letter small subscript v
974,greek subscript small letter beta,1D66,ᵦ,Lm,L,beta greek letter small subscript
975,greek subscript small letter gamma,1D67,ᵧ,Lm,L,gamma greek letter small subscript
976,greek subscript small letter rho,1D68,ᵨ,Lm,L,greek letter rho small subscript
977,greek subscript small letter phi,1D69,ᵩ,Lm,L,greek letter phi small subscript
978,greek subscript small letter chi,1D6A,ᵪ,Lm,L,chi greek letter small subscript
1678,subscript zero,2080,₀,No,EN,subscript zero
1679,subscript one,2081,₁,No,EN,one subscript
1680,subscript two,2082,₂,No,EN,subscript two
1681,subscript three,2083,₃,No,EN,subscript three
1682,subscript four,2084,₄,No,EN,four subscript
1683,subscript five,2085,₅,No,EN,five subscript
1684,subscript six,2086,₆,No,EN,six subscript
1685,subscript seven,2087,₇,No,EN,seven subscript
1686,subscript eight,2088,₈,No,EN,eight subscript
1687,subscript nine,2089,₉,No,EN,nine subscript
1688,subscript plus sign,208A,₊,Sm,ES,plus sign subscript
1689,subscript minus,208B,₋,Sm,ES,minus subscript
1690,subscript equals sign,208C,₌,Sm,ON,equals sign subscript
1691,subscript left parenthesis,208D,₍,Ps,ON,left parenthesis subscript
1692,subscript right parenthesis,208E,₎,Pe,ON,parenthesis right subscript
1693,latin subscript small letter a,2090,ₐ,Lm,L,a latin letter small subscript
1694,latin subscript small letter e,2091,ₑ,Lm,L,e latin letter small subscript
1695,latin subscript small letter o,2092,ₒ,Lm,L,latin letter o small subscript
1696,latin subscript small letter x,2093,ₓ,Lm,L,latin letter small subscript x
1697,latin subscript small letter schwa,2094,ₔ,Lm,L,latin letter schwa small subscript
1698,latin subscript small letter h,2095,ₕ,Lm,L,h latin letter small subscript
1699,latin subscript small letter k,2096,ₖ,Lm,L,k latin letter small subscript
1700,latin subscript small letter l,2097,ₗ,Lm,L,l latin letter small subscript
1701,latin subscript small letter m,2098,ₘ,Lm,L,latin letter m small subscript
1702,latin subscript small letter n,2099,ₙ,Lm,L,latin letter n small subscript
1703,latin subscript small letter p,209A,ₚ,Lm,L,latin letter p small subscript
1704,latin subscript small letter s,209B,ₛ,Lm,L,latin letter s small subscript
1705,latin subscript small letter t,209C,ₜ,Lm,L,latin letter small subscript t
3803,plus sign with subscript two,2A27,⨧,Sm,ON,plus sign subscript two with
4293,latin subscript small letter j,2C7C,ⱼ,Lm,L,j latin letter small subscript

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z